name: Bulk Mobile Traffic Bot

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Run Mobile Bot Script
        run: python main.py
        
